package ui;

/**
 *
 * @author Muhammad Maulana 2310010375
 */
import service.CatatanManager;
import model.Catatan;
import javax.swing.DefaultListModel;

public class CatatFrame extends javax.swing.JFrame {
        CatatanManager manager = new CatatanManager();
        DefaultListModel<Catatan> listModel = new DefaultListModel<>();


    /**
     * Creates new form CatatFrame
     */
    public CatatFrame() {
        initComponents();
        listCatatan.setModel(listModel);
        listCatatan.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            Catatan dipilih = listCatatan.getSelectedValue();
            if (dipilih != null) {
                txtJudul.setText(dipilih.getJudul());
                txtIsi.setText(dipilih.getIsi());
            }
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BgImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCatatan = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIsi = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 254, 229));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Aplikasi Catatan Harian");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        BgImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo LOQ\\Documents\\NetBeansProjects\\UTS_CatatanLana\\img\\Gemini_Generated_Image_k2ow60k2ow60k2ow.png")); // NOI18N
        BgImg.setText("jLabel4");

        jScrollPane1.setViewportView(listCatatan);

        txtIsi.setColumns(20);
        txtIsi.setRows(5);
        jScrollPane2.setViewportView(txtIsi);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Judul Catatan :");

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Isi Catatan :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BgImg, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnLoad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnEdit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnHapus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnSimpan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnTambah))
                    .addComponent(BgImg, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            java.io.FileWriter writer = new java.io.FileWriter("catatan.txt");

            for (int i = 0; i < listModel.size(); i++) {
                Catatan c = listModel.get(i);

                writer.write(c.getJudul() + "\n");
                writer.write("---\n");
                writer.write(c.getIsi() + "\n");
                writer.write("===\n");
            }

            writer.close();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Data berhasil disimpan ke catatan.txt");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal menyimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        try {
            java.io.File file = new java.io.File("catatan.txt");
            if (!file.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "File catatan.txt tidak ditemukan!");
                return;
            }

            java.util.Scanner sc = new java.util.Scanner(file);

            listModel.clear();
            manager.clear(); // tambahkan fungsi ini di manager

            while (sc.hasNextLine()) {
                String judul = sc.nextLine();
                sc.nextLine(); // lewati baris ---
                StringBuilder isi = new StringBuilder();

                String line;
                while (!(line = sc.nextLine()).equals("===")) {
                    isi.append(line).append("\n");
                }

                Catatan c = new Catatan(judul, isi.toString().trim());
                listModel.addElement(c);
                manager.tambah(c);
            }

            sc.close();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Data berhasil dimuat!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal memuat: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = listCatatan.getSelectedIndex();

        if (index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih catatan yang ingin dihapus!");
            return;
        }

        // Konfirmasi sebelum hapus
        int yakin = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus catatan?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (yakin != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // Ambil data
        Catatan dipilih = listModel.getElementAt(index);

        // Hapus dari Manager
        manager.hapus(dipilih);

        // Hapus dari ListModel
        listModel.remove(index);

        // Bersihkan input
        txtJudul.setText("");
        txtIsi.setText("");

        javax.swing.JOptionPane.showMessageDialog(this,
            "Catatan berhasil dihapus!");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int index = listCatatan.getSelectedIndex();

        if (index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih catatan yang ingin diedit!");
            return;
        }

        String judulBaru = txtJudul.getText().trim();
        String isiBaru = txtIsi.getText().trim();

        if (judulBaru.isEmpty() || isiBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Judul dan isi tidak boleh kosong!");
            return;
        }

        // Ambil catatan yang sedang dipilih
        Catatan c = listModel.getElementAt(index);

        // Update data
        c.setJudul(judulBaru);
        c.setIsi(isiBaru);

        // Refresh tampilan list
        listModel.setElementAt(c, index);

        javax.swing.JOptionPane.showMessageDialog(this,
            "Catatan berhasil diperbarui!");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String judul = txtJudul.getText();
        String isi = txtIsi.getText();

        if(judul.isEmpty() || isi.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Judul dan isi tidak boleh kosong!");
            return;
        }

        // 1. Buat objek Catatan baru
        Catatan catatanBaru = new Catatan(judul, isi);

        // 2. Simpan ke manager
        manager.tambah(catatanBaru);

        // 3. Tambah ke listModel supaya tampil di JList
        listModel.addElement(catatanBaru);

        // 4. Bersihkan input
        txtJudul.setText("");
        txtIsi.setText("");

        // 5. Pesan sukses
        javax.swing.JOptionPane.showMessageDialog(this,
            "Catatan berhasil ditambahkan!");
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgImg;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<model.Catatan> listCatatan;
    private javax.swing.JTextArea txtIsi;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
